name: cowsay work-flow

on: push

jobs:
    firt_job:
        runs-on: ubuntu-latest
        steps:
        -   name: git check-out
            uses: actions/checkout@v7

        -   name: list of file
            run: |
                ls -lrt
            
        -   name: install ASCII
            run: |
                chmod 777 cowsay-script.sh
                ./cowsay-script.sh