name: my first github action workflows

on: push

jobs:
    firt_job:
        runs-on: ubuntu-latest
        steps:
        -   name: git check-out
            uses: actions/checkout@v7
            
        -   name: welcome message
            run: echo "Welcome to my CI-CD world"

        -   name: list of file
            run: ls

        -   name: read file
            run: cat README.md